apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  namespace: test-db
  labels:
    app: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: bitnami/mongodb:latest
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
  namespace: test-db
spec:
  selector:
    app: mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
