apiVersion: v1
kind: Secret
metadata:
  name: users-test-db-secret
  namespace: test-db
stringData:
  postgresql-username: admin
  postgresql-password: thepass123
  postgresql-database: users_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-test-db
  namespace: test-db
  labels:
    app: users-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-pg
  template:
    metadata:
      labels:
        app: users-pg
    spec:
      containers:
        - name: users-pg
          image: bitnami/postgresql:13
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: users-test-db-secret
                  key: postgresql-username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-test-db-secret
                  key: postgresql-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: users-test-db-secret
                  key: postgresql-database
---
apiVersion: v1
kind: Service
metadata:
  name: users-test-db-service
  namespace: test-db
spec:
  selector:
    app: users-pg
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
