apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  namespace: converter
  labels:
    app: converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: pychal/converter
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: dotenv
              mountPath: /converter/.env
              subPath: .env
      volumes:
        - name: dotenv
          configMap:
            name: converter-dotenv
