apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: notification
  labels:
    app: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: pychal/notification
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: dotenv
              mountPath: /notification/.env
              subPath: .env
      volumes:
        - name: dotenv
          configMap:
            name: notification-dotenv
