apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-app-dotenv
  namespace: auth-app
data:
  .env: |
    # BASE
    API_V1_PREFIX="/api/v1"
    DEBUG=True
    PROJECT_NAME="Auth App (local)"
    VERSION="0.1.0"
    DESCRIPTION="The API for Authentication app."

    # DATABASE
    DB_ASYNC_CONNECTION_STR="postgresql+asyncpg://admin:thepass123@users-test-db-service.test-db:5432/users_db"
    DB_EXCLUDE_TABLES="[]"

    # AUTH
    JWT_SECRET="eb9fdf01e4f1b556cde951d1ac4e5ad3dd519bc6f0ed67f8fb8a54e757144b1d" # to get a string like this run: openssl rand -hex 32
    JWT_ALGORITHM="HS256"
    JWT_TOKEN_EXPIRE_MINUTES=30
