apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
  namespace: auth-app
spec:
  type: ClusterIP
  selector:
    app: auth-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
